//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRTTIPMERKEZI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MRTTIPMERKEZIDBEntities : DbContext
    {
        public MRTTIPMERKEZIDBEntities()
            : base("name=MRTTIPMERKEZIDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Randevu_tbl> Randevu_tbl { get; set; }
        public virtual DbSet<Kullanicilar_tbl> Kullanicilar_tbl { get; set; }
    }
}
