//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRTTIPMERKEZI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu_tbl
    {
        public int id { get; set; }
        public string TC { get; set; }
        public string AdSoyad { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<System.DateTime> RandevuTarihi { get; set; }
        public string Doktorunuz { get; set; }
    }
}
